// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package carsAPI

import (
	"database/sql"
	"time"
)

type Invoice struct {
	ID        int64         `json:"id"`
	BuyerID   sql.NullInt64 `json:"buyer_id"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

type InvoiceItem struct {
	ID        int64        `json:"id"`
	InvoiceID int64        `json:"invoice_id"`
	VehicleID int64        `json:"vehicle_id"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type User struct {
	ID          int64          `json:"id"`
	FirstName   string         `json:"first_name"`
	MiddleName  sql.NullString `json:"middle_name"`
	LastName    string         `json:"last_name"`
	DateOfBirth time.Time      `json:"date_of_birth"`
}

type Vehicle struct {
	ID          int64        `json:"id"`
	Name        string       `json:"name"`
	Description string       `json:"description"`
	Price       string       `json:"price"`
	Color       string       `json:"color"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}
